name: CI Build Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: install dependencies
        run: |
             python3 -m pip install pyinstaller simpleaudio setuptools

      - name: Build CI
        run: |
             python3 package/build.py

      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: ESC unlocker
          path: |
            esc_unlocker_linux
          retention-days: 7
