name: CI Build Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: install dependencies
        run: |
             sudo apt install alsa-base libasound2-dev python3-tk python3-numpy
             python3 -m pip install pyinstaller simpleaudio setuptools intelhex

      - name: Build CI
        run: |
             python3 package/build.py

      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: ESC unlocker Linux
          path: |
            esc_unlocker_linux
          retention-days: 7
